### ISSUE TITLE
After a reconnect-scheduled, if the login times out, we never connect again

### ISSUE THREAD

**Issue by JohanvdWest** [happner/happn#157]
```
2017-03-21 20:51:12.008 [ INFO] - 1624938ms	satinnape_Ey8B9VpKM (happnerEndpoint) happner-endpoint reconnect/scheduled
2017-03-21 20:51:38.473 [ERROR] - 26468ms	client (HappnClient) unhandled error Error: api request timed out action: login
    at Object.<anonymous> (/node_js/app/node_modules/happn/lib/client/base.js:691:29)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
2017-03-21 20:51:38.482 [ERROR] - Error: api request timed out action: login
    at Object.<anonymous> (/node_js/app/node_modules/happn/lib/client/base.js:691:29)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by JohanvdWest** [comment]
Nice comment describing the problem:
```
// TODO: What happnes if this reconnection login fails?
//       Who gets told?
//       How?
```
