### ISSUE TITLE
Uncaught TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by JensEggers** [happner/happn#176]
Spotted on device-registration-components test on travis, does not occur frequently, but points to a need for more defensive code.
```
1) 12-alarm-status.js "before all" hook:
     Uncaught TypeError: Cannot read property 'data' of undefined
      at SecurityService.serialize (node_modules/happn/lib/services/security/service.js:1057:45)
      at node_modules/happn/lib/services/security/service.js:1419:32
      at node_modules/happn/lib/services/data/service.js:470:7
      at newArguments.(anonymous function) (node_modules/happn-nedb/lib/executor.js:29:17)
      at Cursor.execFn (node_modules/happn-nedb/lib/datastore.js:485:12)
      at callback (node_modules/happn-nedb/lib/cursor.js:131:19)
      at node_modules/happn-nedb/lib/cursor.js:198:12
      at node_modules/happn-nedb/lib/datastore.js:330:16
      at Object.async.eachSeries (node_modules/happn-nedb/node_modules/async/lib/async.js:130:20)
      at node_modules/happn-nedb/lib/datastore.js:324:13
      at fn (node_modules/happn-nedb/node_modules/async/lib/async.js:582:34)
      at Immediate.<anonymous> (node_modules/happn-nedb/node_modules/async/lib/async.js:498:34)
```

**Comment by JensEggers** [comment]
https://github.com/happner/happn/blob/master/lib/services/security/service.js#L1055

**Comment by JensEggers** [comment]
@southbite pls take a look and also see if a similar issue exists in happner-2
