### ISSUE TITLE
[FATAL] - TypeError: Cannot redefine property: post

### ISSUE THREAD

**Issue by JensEggers** [happner/happn#25]
When using the meshClient (in browser or PC) we sometimes seeing this error:

[FATAL] - 7147ms bristlethumb_4kEDD2hul (Mesh) uncaughtException (or set NO_EXIT_ON_UNCAUGHT) [TypeError: Cannot redefine property: post]
[FATAL] - TypeError: Cannot redefine property: post
at Function.defineProperty (native)
at Object.Internals._initializeLocal (/node_js/node_modules/happner/lib/system/shared/internals.js:25:12)
at Object.handler (/node_js/node_modules/happner/lib/system/shared/mesh-client.js:293:21)
at Object. (/node_js/node_modules/happn/lib/client/base.js:359:16)
at HappnClient.handle_response_array (/node_js/node_modules/happn/lib/client/base.js:526:19)
at HappnClient.handle_publication (/node_js/node_modules/happn/lib/client/base.js:486:11)
at Primus.emit (events.js:98:17)
at done (primus.js:2243:48)
at transform (primus.js:2214:30)
at Primus.transforms (primus.js:2235:4)
at decoding (primus.js:2012:14)
at Primus.decoder (primus.js:2817:3)
at Primus.message (primus.js:2001:12)
at Primus.emit (events.js:95:17)
at next (primus.js:140:17)
at defer as _onTimeout

**Comment by JensEggers** [comment]
closing in favour of https://github.com/happner/issues/70 (the original issue was reported here)
